### ISSUE TITLE
Betagal pass-through on GPU machines

### ISSUE THREAD

**Issue by kuybeda** [KryoEM/AAProject#11]
A pass through test to make sure all modules work well with no importance for high res reconstruction

**Comment by darthweider** [comment]
Will wait until after @a-re has pushed all necessary changes to unblur_tbz

**Comment by darthweider** [comment]
In the meantime, any thoughts on how to get the massive raw .tbz data over to the GPU machines?

Should I just do rsync or will we want something more sophisticated? @a-re @kuybeda

**Comment by kuybeda** [comment]
I have been using filezilla from a vnc service running on one of my
machines.

Rsync would be a good command line option. You could just run it on one
machine, which will takeabout half an hour.

**Comment by a-re** [comment]
@darthweider, the unblur_tbz integration should be complete. I am currently testing it on Amazon EC2, but the code is finished and free of any major bugs.

**Comment by darthweider** [comment]
Pass-through has completed with a final resolution of 2.5Å.

Further testing will be conducted to attempt to get higher resolution.
