### ISSUE TITLE
CUDA library paths

### ISSUE THREAD

**Issue by darthweider** [KryoEM/AAProject#24]
Implement mechanism that defines custom cuda settings for each auxiliary relion module. 
This includes customizing and testing gctf abd motioncorr2 modules.
-----------------------------------------------------------------------------
gctf executables available at: /mnt/shared/relion/Gctf/Gctf_v1.06/

Running gctf produces an error:
$ ../apps/RELION/Gctf/Gctf_v1.06/bin/Gctf-v1.06_sm_20_cu8.0_x86_64 
../apps/RELION/Gctf/Gctf_v1.06/bin/Gctf-v1.06_sm_20_cu8.0_x86_64: error while loading shared libraries: libcufft.so.8.0: cannot open shared object file: No such file or directory

I believe this is because we need to add the CUDA libraries to the environment in ~/.bashrc

Also see the Gctf troubleshooting manual:  http://www.mrc-lmb.cam.ac.uk/kzhang/Gctf/GPU_Trouble_Shooting.pdf

**Comment by kuybeda** [comment]
most probably, LD_LIBRARY_PATH needs to point to the cuda 8.0 library location. 

It looks like different Relion components may need to use different CUDA environments. A possible solution is to replace the stock execution commands (like gctf) for example by scripts that first export the correct  LD_LIBRARY_PATH that is required by that program and then calls to the stock execution command. The default LD_LIBRARY_PATH shall point to CUDA environment that is required by the core Relion programs, which is probably 7.5, or 8.0. Let's discuss this and do this change when we meet.

**Comment by darthweider** [comment]
LD_LIBRARY_PATH was indeed the problem.

- Switched to h1018, which includes the shared drive CUDA location in its $PATH and $LD_LIBRARY_PATH. [Alex should be adding that environment to the other machines as well.]

- because sudo resets these environment variables, in order to run make as sudo, one needs to do: 'sudo -i make'
To emulate this in the playbook, I changed the become flag:

> - name: Install Relion and auxiliary software on shared drive
>   hosts: installer
>   become: yes
>   become_flags: '-i'
>   roles:
>     - shared_relion
