### ISSUE TITLE
Stage I Betagal

### ISSUE THREAD

**Issue by kuybeda** [KryoEM/AAProject#25]

**Comment by kuybeda** [comment]
Stage I - using the latest 2.3Å Betagal Relion result
      -  Extract first 20 movie frames (currently pre-polished process seems to use all 38 frames)
      -  Produce averaged micrographs using dose weighting + motion correction (via unblur)
      -  Extract particles using the coordinates from the 2.6Å map above
      -  Run refinement staring from 20A initial

     This stage shall result in a map better or equal to 2.6Å.

**Comment by darthweider** [comment]
Undergoing refinement.

**Comment by darthweider** [comment]
Refinement completed. Motion correction using unblur (no dose-weighting). Refined map at 3.1Å. 

Potentially higher resolution with re-grouping?
