### ISSUE TITLE
Stage III Betagal

### ISSUE THREAD

**Issue by kuybeda** [KryoEM/AAProject#27]
Stage III: 
   - polish particles using all 38 frames and ~2.5Å map
   - Refine with 20Å initial
This stage will get us a little bit, because polishing is done with a higher res map

**Comment by darthweider** [comment]
Re-open #38 (document unit test process) if this task is completed.

**Comment by kuybeda** [comment]
No need to do it, as pass-through reaches 2.5A without polishing.
