### ISSUE TITLE
Set up CUDA environment on all machines

### ISSUE THREAD

**Issue by darthweider** [KryoEM/AAProject#31]
run CUDA playbook to create /etc/profile.d/ script that will set up cuda environment variables

**Comment by kuybeda** [comment]
Troubleshoot why CUDA environment setup script was only to the server node h1018. Fix the CUDA setup playbook to copy it to all nodes.

**Comment by kuybeda** [comment]
@a-re : Has this task been done already?

**Comment by arestifo** [comment]
Yes, the cuda.sh script should be in /etc/profile.d for all machines
