### ISSUE TITLE
Sanity check script for Relion install

### ISSUE THREAD

**Issue by darthweider** [KryoEM/AAProject#37]
At the end of Relion install playbook, print out a message telling the user a few simple commands to try out to test that Relion is working correctly.
i.e. "now run this: ____; if it works, then your Relion setup is complete"

* minimize time for test
* maximize number of dependencies tested
* maybe use something that is part of the unit test

**Comment by kuybeda** [comment]
What about doing a single refinement iteration at 40A resolution using all nodes involved in the installation. How long this run may take? We also may reduce number of particles to 10k for that. If it takes minutes, so we can add this as a sanity check. We shall run this fast unit test, record the resulting output params, such as resolution after one iteration and some other outputs and compare that with the result of the sanity check at the end of Relion installation. 

When we are ready with automated drift and ctf corrections, we can add more unit tests to the sanity check as well.

**Comment by darthweider** [comment]
Refinement is a little difficult because it looks like it cannot be manually set to stop at 1 iteration.

Instead, I will do 3D classification, which is a submodule of the relion_refine_mpi program as well. 10k particles, classified into 1 class (effectively quite similar to refinement).

Two iterations will take 10 minutes, and should take us from 40Å initial model to 20Å map. (iteration 1 is too similar to iteration 0 to assess well)

I'll call 5 mpi processes with a command such as:
```source /etc/profile.d/relion.sh; mpirun -np 5 `which relion_refine_mpi` --o Class3D/run --i /shared/data/betagal_unittest/shiny_particles_10k.star --ref /shared/data/betagal_unittest/References/5a1a_4A_bin3.mrc --firstiter_cc --ini_high 40 --dont_combine_weights_via_disc --scratch_dir /scratch/relion_install_check/ --pool 3 --ctf --ctf_corrected_ref --iter 2 --tau2_fudge 4 --particle_diameter 200 --K 1 --flatten_solvent --zero_mask --oversampling 1 --offset_range 5 --offset_step 2 --sym D2 --norm --scale  --j 4 > class3d.out 2> class3d.err```

**Comment by kuybeda** [comment]
Using 3D classification sounds good and getting from 40A to 20A would give
us a quality measure that is good enough.

However, I would suggest to find a way to distribute the processing among
all machines to test connectivity and basic setup on every node.

For example, you can do it by using hosts file and assigning 2 slots per
host. Then calling 7 mpi ranks would distribute the work among all nodes.

**Comment by darthweider** [comment]
Finally completed and pushed.

Added installation of Git LFS to retrieve a downsized (10k particles) and downsampled (bin x16) unit test.

Runs Class3D for two iterations, with two processes assigned to each host listed in the playbook.  Takes ~3mins on four machines (two processes each), since the unit test is downsampled.
