### ISSUE TITLE
integrate mpirun of unblur_tbz.py

### ISSUE THREAD

**Issue by kuybeda** [KryoEM/AAProject#41]
Follow and update the following doc https://docs.google.com/document/d/1AnYH_BgtgxXu6JBnvjn_lRJNMk4ByngwKt31JAFnqV0/edit?usp=sharing

in order to add support for unblur_tbz.py into Relion pipeline

This script allows to run unblur/summovie via MPI on star file that with tbz-compressed movies. This task would conclude when mpirun unblur_tbz.py works on our GPU machines

**Comment by darthweider** [comment]
Playbook updated to include installation of Anaconda and mpi4py.

Current installation requires exporting environment variables to mpiexec, in order to recognize Anaconda bin paths, e.g.:
mpiexec -n 5 -x PATH python mpi4py.git/demo/helloworld.py

**Comment by darthweider** [comment]
Playbook updated to install custom Relion and python scripts. No compile time errors.

Will test for runtime errors on real Csy dataset.

**Comment by kuybeda** [comment]
What about our custom startup script that sets environment per each Relion
command? It looks like you will need to use it as well.  As discussed, it
should be able to source profile.d.

If seems that you will need that sooner than Alex would be able to take
care of that, you are welcome preempt that task.

**Comment by darthweider** [comment]
I can work on that, but I'll make a separate task for it

**Comment by darthweider** [comment]
Successfully ran unblur_tbz on Csy dataset using a wrapper script that sources /etc/profile.d

`mpirun -n 5 /shared/processCsy/Csy_dsDNA/sourced.sh
`

contents of ./sourced.sh:
```
#!/bin/bash


for file in /etc/profile.d/*; do source $file; done

`which unblur_tbz.py` -i 375mic.star -o Unblur/ -j 4 -f 2 -l 20 -un /shared/relion/Unblur/unblur_1.0.2/bin/unblur_openmp_7_17_15.exe -sm /shared/relion/Summovie/summovie_1.0.2/bin/sum_movie_openmp_7_17_15.exe > unblur_tbz.out 2> unblur_tbz.err
```


Separate issue opened regarding setting up environment variables generally: #45
