### ISSUE TITLE
Add Relion GUI support for unblur_tbz.py

### ISSUE THREAD

**Issue by kuybeda** [KryoEM/AAProject#43]
Once unblur_tbz.py can be successfully run via command line, it should be added as a separate item to be able to get invoked from Relion GUI

**Comment by darthweider** [comment]
Relion GUI needs to call mpirun, I think.

Currently, hitting run on the GUI will run the command:
``for file in /etc/profile.d; do . $file; done; `which unblur_tbz.py` -i tbz.star -o UnblurTBZ/job001/ -f 3 -l 21 -un /shared/relion/Unblur/unblur_1.0.2/bin/unblur_openmp_7_17_15.exe -sm /shared/relion/Summovie/summovie_1.0.2/bin/sum_movie_openmp_7_17_15.exe
``
unblur_tbz will then complain that it doesn't have enough ranks and fail.


I think the easiest solution is to either
1) have a wrapper script that calls the sourcing step
the GUI will run the command `mpirun unblur_tbz_wrapper.py -i tbz.star -o UnblurTBZ/job001/ ....`  

2) integrate the sourcing step into the unblur_tbz.py code
and then the GUI can just run `mpirun unblur_tbz.py -i tbz.star .....`

**Comment by kuybeda** [comment]
Can this issue be closed?
