### ISSUE TITLE
profile.d doesn't get updated

### ISSUE THREAD

**Issue by kuybeda** [KryoEM/AAProject#44]
It looks like CUDA installation playbook does not create the shell script in profile.d. Please delete the CUDA scripts in all nodes and rerun the playbook to make sure that the script gets created using 'touch' command within the script

**Comment by a-re** [comment]
I just deleted the cuda.sh (cuda environment) script in /etc/profile.d on all the machines and reran the playbook, everything seemed to work fine and the script was placed in /etc/profile.d/. Is this the script you were talking about?

**Comment by kuybeda** [comment]
Thanks Alex for testing that out!

For some reason, cuda.sh was not created on my machines when I ran nvidia
drivers playbook there. If it works from scratch on the new machines, then
I would not worry to much what went wrong in my case for now.

Thanks,
Oleg.
