### ISSUE TITLE
Set environment variables for mpirun

### ISSUE THREAD

**Issue by darthweider** [KryoEM/AAProject#45]
mpirun produces non-interactive shells on all hosts, and therefore they do not source /etc/profile.d

Currently, we can get around this by setting the environment in the command passed to mpirun, e.g. the following passes the current login shell's $PATH variable to each MPI process:

mpirun -n 5 -x PATH python demo/helloworld.py

Ideally, however, mpirun would source environment variables without the human user needing to remember and specify all of them.

**Comment by arestifo** [comment]
I found a couple solutions:

* Passing a run script to mpirun that loads the environment variables on the worker nodes and then executes the command. This is probably the cleanest solution.
* The file `/etc/environment` is loaded for all shells, interactive/non-interactive/login/non-login, and any variable put there is systemwide. We could use this to permanently set any variables we need.
* Use the [SLURM](https://slurm.schedmd.com/) batch system with the [LMOD](https://www.tacc.utexas.edu/research-development/tacc-projects/lmod) module system (the solution biowulf uses). This would allow us to quickly switch environment and have them propagate over all the nodes the job is submitted to, but it might be overkill.

**Comment by darthweider** [comment]
The /etc/environment option sounds good to me, since we'd just have to port what we have in profile.d over there.

My only concern is if we'd be able to use variables when defining the environment. For example, right now in profile.d, we can do things like PATH=$PATH:/shared/app/bin/
But if /etc/environment gets loaded for all shells, I'm worried that we'll have a login shell run a program in a subshell, and then the login shell's PATH variable gets passed to the subshell, but the subshell runs /etc/environment and appends more stuff onto the PATH variable, etc. and it'll end up a garbled mess with enough subshells.

**Comment by darthweider** [comment]
Will be solved by using a template submission script. See #35
