### ISSUE TITLE
Clean up Relion playbook variables

### ISSUE THREAD

**Issue by kuybeda** [KryoEM/AAProject#51]
relion_install/README.md: Explain group_vars/all customization options before mentioning how to run playbook (that will need these params to be properly defined beforehand).

**Comment by darthweider** [comment]
Will move all variables that require user input to inventory file, and also prompt user at the beginning of the play to check that the inventory has been checked.

**Comment by darthweider** [comment]
More or less done; will run tomorrow on the machines to test for errors.

**Comment by darthweider** [comment]
Tested; done.

Figured out a way for the playbook to find out where Cuda is. The only variables the user needs to indicate are the install directory and the scratch directory.
