### ISSUE TITLE
Change playbook to install stable Relion release

### ISSUE THREAD

**Issue by darthweider** [KryoEM/AAProject#52]
Email from Scheres to 3DEM listserv:
We have moved the stable code from bitbucket to
https://github.com/3dem/relion. For those of you who participated in
beta-testing, please download and re-install the latest version from
there, as the bitbucket repository is no longer available. Detailed
instructions on installation and how to use the new parts of the
software have been added to the RELION Wiki.

**Comment by darthweider** [comment]
Will wait for completion of beta-gal run-through on current installation of Relion 2.0.2 beta before attempting this.

**Comment by darthweider** [comment]
Playbook is set to pull from the 'master' branch of our custom repository. Once we determine that 2.0.3 is stable via the developer tbzmotion branch, we will merge with the 'master' branch and the playbook will be able to install 2.0.3 automatically.

**Comment by kuybeda** [comment]
it could be useful to include the branch name in the inventory file. The
default will be 'master', but it may save efforts (and errors) if the
playbook will be able to take install the branch by demand

**Comment by darthweider** [comment]
Done
