### ISSUE TITLE
Scratch permissions

### ISSUE THREAD

**Issue by darthweider** [KryoEM/AAProject#53]
I'm getting errors from mpirun jobs where the workers don't have write access to the scratch directory.

I'm thinking to change the scratch directory's permissions to 777 in the relion playbook, if no one is opposed.

**Comment by arestifo** [comment]
I modified the beegfs playbook to assign the permissions of 1777 to both /shared and /scratch. The 1 in the permission just prevents other users from deleting/editing the files, which is good from a security perspective. It shouldn't have any implication if we're using ubuntu for all administrative tasks.
