### ISSUE TITLE
Test relion install playbook with Amazon EC2

### ISSUE THREAD

**Issue by arestifo** [KryoEM/AAProject#55]
To test the relion playbook, we can set up an Amazon EC2 cluster that will have a similar setup to the cluster we have now. Running the relion install playbook on these machines should help with debugging and making sure the playbook works from a fresh install of Ubuntu.

**Comment by arestifo** [comment]
I am in the process of testing the relion playbook and am coming across an error that I can't figure out:

    TASK [shared_relion : Check if CUDA installed] *********************************
    fatal: [localhost]: FAILED! => {"failed": true, "msg": "{{cuda_install_dir}}bin/: {{ cuda_existing_dir |             default( {{ shared_dir }}cuda/cuda-8.0/ ) }}: template error while templating string: expected token ':', got '}'. String: {{ cuda_existing_dir | default( {{ shared_dir }}cuda/cuda-8.0/ ) }}"}
    ...ignoring


    TASK [shared_relion : pause] ***************************************************
    fatal: [localhost]: FAILED! => {"failed": true, "msg": "The conditional check 'nvcc_80|failed' failed. The error was: {'msg': u\"{{cuda_install_dir}}bin/: {{ cuda_existing_dir | default( {{ shared_dir }}cuda/cuda-8.0/ ) }}: template error while templating string: expected token ':', got '}'. String: {{ cuda_existing_dir | default( {{ shared_dir }}cuda/cuda-8.0/ ) }}\", 'failed': True}: template error while templating string: expected token ':', got '}'. String: {{cuda_install_dir}}bin/: {{ cuda_existing_dir | default( {{ shared_dir }}cuda/cuda-8.0/ ) }}: template error while templating string: expected token ':', got '}'. String: {{ cuda_existing_dir | default( {{ shared_dir }}cuda/cuda-8.0/ ) }}\n\nThe error appears to have been in '/home/ubuntu/aaproject/relion_install/roles/shared_relion/tasks/main.yaml': line 12, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- pause:\n  ^ here\n"}

I think it may have to do with the fact that variables and ansible functions are not supported in the group_vars/all file, but I'm not sure because variables are used extensively in the group_vars/all

**Comment by darthweider** [comment]
Taking a look.

**Comment by darthweider** [comment]
Are you sure you have the latest version of the playbook?


Last push from me was 3 days ago, and that task should have been changed to:
```
- name: Check if CUDA installed 
  shell: "nvcc --version | grep '8.0'"
  register: nvcc_80
  environment:
    PATH: "{{ansible_env.PATH}}:{{cuda_bin}}"
    LD_LIBRARY_PATH: "{{cuda_lib}}"
  ignore_errors: true # do not stop playbook if CUDA not found
```

**Comment by arestifo** [comment]
Yeah, git pull says that the repo is up to date

**Comment by darthweider** [comment]
Sorry, my fault -- I had some uncommited changes.

If you try to pull again, git should hopefully pull the right cuda check.
