### ISSUE TITLE
move all data and 3d party to s3

### ISSUE THREAD

**Issue by kuybeda** [KryoEM/AAProject#58]
move all large files involved in the Relion install to s3.

**Comment by a-re** [comment]
We need to open an aws account we all have access to. I would just open an account with a shared password, but aws requires a credit card on file even for the free services.

**Comment by kuybeda** [comment]
I will register an account and send you the details.

**Comment by a-re** [comment]
Files that need to be put on s3:
Motioncorr: `http://cryoem.ucsf.edu/software/motioncorr_v2.1.tar`
Unblur: `http://grigoriefflab.janelia.org/sites/default/files/unblur_1.0.2.tar.gz`
Summovie: `http://grigoriefflab.janelia.org/sites/default/files/summovie_1.0.2.tar.gz`
CTFFIND: `http://grigoriefflab.janelia.org/sites/default/files/ctffind-4.1.5-linux64.tar.gz`
GCTF: `http://www.mrc-lmb.cam.ac.uk/kzhang/Gctf/Gctf_v1.06_and_examples.tar.gz`
ResMap: `http://downloads.sourceforge.net/project/resmap/ResMap-1.1.4-linux64?r=&ts=1480697023`
IMOD: `http://bio3d.colorado.edu/imod/AMD64-RHEL5/imod_4.7.15_RHEL6-64_CUDA6.0.csh`
Anaconda: `https://repo.continuum.io/archive/Anaconda2-4.2.0-Linux-x86_64.sh`
MotionCorr2: `http://msg.ucsf.edu/MotionCor2/MotionCor2-10-19-2016.tar.gz`

**Comment by darthweider** [comment]
There's a new version of MotionCor2:
`http://msg.ucsf.edu/MotionCor2/MotionCor2-01-30-2017.tar.gz
`
It's not in the playbook yet, but I am planning to add it when I change the playbook to install Relion 2.0.3 stable.

**Comment by kuybeda** [comment]
Thanks, I'll put it as well to the S3.

**Comment by kuybeda** [comment]
Here they are. Please let me know how it works for you.

https://s3.amazonaws.com/kryoem/AAProject/Anaconda2-4.2.0-Linux-x86_64.sh
https://s3.amazonaws.com/kryoem/AAProject/Gctf_v1.06_and_examples.tar.gz
https://s3.amazonaws.com/kryoem/AAProject/MotionCor2-01-30-2017.tar.gz
https://s3.amazonaws.com/kryoem/AAProject/MotionCor2-10-19-2016.tar.gz
https://s3.amazonaws.com/kryoem/AAProject/ResMap-1.1.4-linux64
https://s3.amazonaws.com/kryoem/AAProject/ctffind-4.1.5-linux64.tar.gz
https://s3.amazonaws.com/kryoem/AAProject/imod_4.7.15_RHEL6-64_CUDA6.0.csh
https://s3.amazonaws.com/kryoem/AAProject/motioncorr_v2.1.tar
https://s3.amazonaws.com/kryoem/AAProject/summovie_1.0.2.tar.gz
https://s3.amazonaws.com/kryoem/AAProject/unblur_1.0.2.tar.gz

**Comment by kuybeda** [comment]
What about sanity check data?

**Comment by darthweider** [comment]
Uploaded on Dropbox temporarily so you can download it:
https://www.dropbox.com/s/9ld28vbeltiuee9/unittest_tiny.tar.gz?dl=0

After we test that the Amazon link works, we can pull out the roles for installing Git Large File Storage.

**Comment by kuybeda** [comment]
Gere is the link:

https://s3.amazonaws.com/kryoem/AAProject/unittest_tiny.tar.gz

**Comment by a-re** [comment]
Just a note for when we transition to git LFS, when I try to download the unit test from LFS, the playbook errors saying we are over our bandwidth limit. I have the playbook downloading from S3 now, but just a heads up for when we start using LFS.

**Comment by darthweider** [comment]
Are we planning to transition to git LFS?

**Comment by darthweider** [comment]
Not using git-lfs. Everything should be moved.
