### ISSUE TITLE
No write protection for scratch child dirs

### ISSUE THREAD

**Issue by darthweider** [KryoEM/AAProject#64]
Any user should be able to delete a directory inside scratch that is not in use. 

Currently, only the user that created the directory can delete it.

**Comment by kuybeda** [comment]
Shall be set as a part of relion install playbook. Has anything been done on this issue so far?

**Comment by arestifo** [comment]
Fixed using `for i in {1..4}; do ssh -t node$i sudo chmod -R 0777 /mnt/scratch/*; done` Also fixed the command in the BeeGFS playbook that caused this behavior to occur.
