### ISSUE TITLE
Add default hostfile environment variable

### ISSUE THREAD

**Issue by darthweider** [KryoEM/AAProject#68]
RELION_DEFAULT_HOSTFILE should be placed in profile.d by Ansible

**Comment by darthweider** [comment]
Ansible should also by default figure out how many GPUs are available on each host


See results of `ansible -m setup localhost > setup.txt` for available facts.

**Comment by darthweider** [comment]
@a-re I just want to confirm that RELION_DEFAULT_HOSTFILE is the right environment variable name that your custom Relion 2.0 is looking for.

This environment variable already gets created in `/etc/profile.d/relion_custom.sh`:
```
RELION_DEFAULT_HOSTFILE="/shared/apps/Relion2.0/relion2.0_custom_dev/mpirun_default.hosts"
```
so I'm not quite sure why it isn't being recognized when I start up the Relion GUI.

**Comment by arestifo** [comment]
Yes, that's the right one. I'll look into why it's not being recognized

**Comment by darthweider** [comment]
Note:

`ls -l /proc/driver/nvidia/gpus/ | wc -l` will give count of how many nvidia gpus.

**Comment by darthweider** [comment]
Done.
